### ISSUE TITLE
Refreshing chat exposes older comments instead of most recent

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/forums.openusercss.org#11]

**Comment by DecentM** [comment]
I'm not sure what you mean with this one, can you explain in detail?

**Comment by RaitaroH** [comment]
@DecentM Told you too look into your chat in the forums.

**Comment by DecentM** [comment]
I can see a bunch of references to Raven, which is probably due to your filters. Can you try turning them off and seeing if that solves it?
