### ISSUE TITLE
Remove theme selection box from profile settings

### ISSUE THREAD

**Issue by DecentM** [OpenUserCSS/forums.openusercss.org#12]

**Comment by RaitaroH** [comment]
It has such a thing?

**Comment by DecentM** [comment]
![](https://i.ytimg.com/vi/qRC4Vk6kisY/maxresdefault.jpg)

**Comment by RaitaroH** [comment]
![](https://avantwhat.files.wordpress.com/2011/08/serial_experiments_lain-14373.jpg)
