### ISSUE TITLE
Share accounts between main site and forum

### ISSUE THREAD

**Issue by hyperfekt** [OpenUserCSS/forums.openusercss.org#14]
Given that the forum is the official avenue for communication on OpenUserCSS, we would want to avoid both impersonation and the hassle of registering again by using the accounts from the main site on the forum.

**Comment by DecentM** [comment]
Thanks for the feedback!  
This issue is already being tracked at https://github.com/OpenUserCSS/openusercss.org/issues/14 for v1.0.0. Please follow that thread for updates.

**Comment by hyperfekt** [comment]
Woops. Thanks for the pointer! I should have expected this to be tracked already.
