### ISSUE TITLE
@ not responding

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/forums.openusercss.org#15]
Ey @DecentM is it me or on the forum @ doesn't actually give you a handle nor does it actually turn into a link. Example here: https://forums.openusercss.org/topic/20/google-dark-search/14

**Comment by DecentM** [comment]
Thanks for reporting this!  
It looks like the mentions plugin is broken, I'll take a look in the next maintenance period.

**Comment by DecentM** [comment]
Fixed with the latest maintenance window
