### ISSUE TITLE
You don't seem to have a compatible extension installed

### ISSUE THREAD

**Issue by the-j0k3r** [OpenUserCSS/forums.openusercss.org#18]
![capture](https://user-images.githubusercontent.com/31389848/41122908-f0291a2e-6a94-11e8-8923-cd93260bc528.PNG)

Disabling blockers and all addons exept Stylus behaves same.

**Comment by DecentM** [comment]
Since this issue is on the main site, please open it in the site's repo: https://github.com/OpenUserCSS/openusercss.org/issues.  

I'd be happy to take a look if you can provide some info about your environment that the issue template asks for there :+1:
