### ISSUE TITLE
Button out of alignment.

### ISSUE THREAD

**Issue by the-j0k3r** [OpenUserCSS/forums.openusercss.org#19]
This is the only button I can see in all dialogs in forums well out of alignment in user profile in forums.

![capture](https://user-images.githubusercontent.com/31389848/41439707-b7933386-7023-11e8-9352-f319983ad21f.PNG)

I tried fixing it but fix one and break another.

```html
<div class="form-actions">
		<a id="submitBtn" href="#" class="btn btn-primary">Save Changes</a>
	</div>
```

**Comment by the-j0k3r** [comment]
Also when you define no style you get grey icons and text on header against that blinding blue which is exacerbated by the white and hates everyone's retinas.

![screenshot-2018-6-16 openusercss](https://user-images.githubusercontent.com/31389848/41501893-dab1fc44-71a4-11e8-8b2f-a897952fae4e.png)

**Comment by DecentM** [comment]
It doesn't seem to make sense to have a skin changer when you have some great themes to the site, so I think I'll remove the skin selector in the next maintenance window.  

Thanks for reporting!

**Comment by the-j0k3r** [comment]
> It doesn't seem to make sense to have a skin changer when there are some great themes to the site

I guess doesnt make sense for a website dedicated to creating themes.

I wouldn't remove it anywho, the CSS from some of those styles may be helpful in creating themes in future.
