### ISSUE TITLE
HUge, longer than full width notification boxes

### ISSUE THREAD

**Issue by DecentM** [OpenUserCSS/forums.openusercss.org#20]
_From @the-j0k3r on June 16, 2018 19:51_

| Expected behaviour | Actual behaviour |
| ------------------ | ---------------- |
| What you expected the site to do | What the site actually did |
| decent size notification boxes like before. |HUGE long ones instead|

## Steps to Reproduce the Problem

  1.goto forums user account settings
  1. upload a background header
  1. adjust header
  1. see extra long notification boxes (bottom) that run off screen (longer than 2560x 1440p hahaha. NICE!

![untitled-1](https://user-images.githubusercontent.com/31389848/41501995-33e8f086-71a7-11e8-82c5-6db0801d0cc1.png)

## Environment details

  - Site version: 1.4.1 - 1.4.4 (forums update?) idk I can copy this to forum bugs
  - Browser and version: FF 66.0.2
  - Installed extensions: Stylus
  - Operating system: Win 10 pro

----

<details>
  <summary><strong>Stack trace</strong> (click to expand)</summary>

  ```
  {{trace here}}
  ```
</details>

_Copied from original issue: OpenUserCSS/openusercss.org#112_

**Comment by DecentM** [comment]
Thanks for reporting!  
This doesn't happen for me. Try disabling the theme to see if that causes it!

**Comment by the-j0k3r** [comment]
Never mind its this code https://github.com/OpenUserCSS/openusercss.org/issues/30#issuecomment-354657500

**Comment by the-j0k3r** [comment]
@DecentM the specific portion of that which affects these is.

```css
html,
body,
html body.v--modal-block-scroll,
body > div,
.route-root,
.navbar {
    width: 100vw!important;
}
```

So you know :)

**Comment by DecentM** [comment]
Oh, thanks! I'll look into it in the next maintenance window.

**Comment by the-j0k3r** [comment]
Eh thats custom style to fix scrollbars its not even used, Ifixed it by setting a new rule only for `body > div` with auto width.

**Comment by DecentM** [comment]
I was unable to reproduce this after the maintenance, so I'm assuming this is either fixed or caused by something else I can't control. I'll close this, but feel free to reopen if it's still happening.
