### ISSUE TITLE
Site certificate invalid

### ISSUE THREAD

**Issue by CobaltSpace** [OpenUserCSS/forums.openusercss.org#24]
Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for forums.openusercss.org. The certificate is only valid for 5d5e8eb104dbaea44ad1db4ca43175f8.1c8f634e5b1ccdc36238caa8946bfcc4.traefik.default.

**Comment by DecentM** [comment]
Thanks for letting me know, I'll fix it as soon as I can.

**Comment by DecentM** [comment]
Should be all good now, I've messed up a migration between servers. Thanks again!

If the issue still persists after a few minutes, please let me know.
