### ISSUE TITLE
Can't login in the forum

### ISSUE THREAD

**Issue by decembre** [OpenUserCSS/forums.openusercss.org#25]
When i can login in the site , i can't loin into the forum.
My username:
decembre

**Comment by DecentM** [comment]
:wave: The forums are using separate accounts from the main site, so you'll need to register separately. You may use the same e-mail you used for the main site to keep it consistent, or you may use a different one.

**Comment by decembre** [comment]
Strange ...
1 year ago, i have posted in it with the same account than the main site:
[Problem to post a theme : Entity Too Large](https://forums.openusercss.org/topic/25/problem-to-post-a-theme-entity-too-large)
