### ISSUE TITLE
Github embeds spacing

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/forums.openusercss.org#6]
![image](https://user-images.githubusercontent.com/19552720/35637156-125336d0-06bc-11e8-8eaf-aa8415c10ee5.png)

Somewhat better in the compact (modal) form:
![image](https://user-images.githubusercontent.com/19552720/35638701-7f2f1680-06c0-11e8-9171-7bf9f5721c63.png)

**Comment by DecentM** [comment]
Thanks for reporting!
