### ISSUE TITLE
Connection to Openusercss was lost

### ISSUE THREAD

**Issue by DecentM** [OpenUserCSS/forums.openusercss.org#8]
_From @tkosamja on February 4, 2018 9:49_

Whenever I log in to the forum, the following message appears:
`Looks like your connection to OpenUserCSS was lost, please wait while we try to reconnect.`
I can't post or send any chat messages.

_Copied from original issue: OpenUserCSS/openusercss.org#72_

**Comment by DecentM** [comment]
I'm unable to reproduce this, can you post some details about your environment? (OS version, browser, extensions, etc)

**Comment by tkosamja** [comment]
It's working now, weird.

**Comment by DecentM** [comment]
Alright, let me know if this is a returning issue

**Comment by tkosamja** [comment]
Will do
