### ISSUE TITLE
Check as unread should have some tooltip

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/forums.openusercss.org#9]
![image](https://user-images.githubusercontent.com/19552720/36342123-4aeeb0de-1402-11e8-9760-5680dc9e5d5a.png)
See that circle... yeah it should tell you what it does when you hover.

**Comment by DecentM** [comment]
I'll look into this in the next maintenance window. Thanks!

**Comment by DecentM** [comment]
Done, inserted a new ::before element with CSS :tada:

**Comment by RaitaroH** [comment]
There you go :P
